[package]
name = "kvproto"
version = "0.0.1"
keywords = ["TiKV"]

[lib]
name = "kvproto"

[dependencies]
protobuf = "~2.0"
futures = "0.1"
# grpcio = "0.4"
raft = "0.3"

[dependencies.grpcio]
git = "https://github.com/hicqu/grpc-rs"
branch = "v0.4"
